# Workflow for building and deploying sphinx documentation to GitHub Pages
name: Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, master, feature/issue-17/github-pages-docs]
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "gh-pages-docs"
  gh-pages-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Upgrade pip
      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
          
      - name: Install dependencies
        run: |
          # pip install sphinx sphinx_click furo sphinx_rtd_theme myst_parser
          pip install -r docs/requirements.txt
          pip install .

      # Build the sphinx api docs
      - name: Sphinx build reference docs
        run: |
          cd docs/
          make apidoc
      
      # Build the html pages
      - name: Sphinx build html pages
        run: |
          cd docs/
          make html

      # - name: Sphinx build docs
      #   run: |
      #     sphinx-build docs _build

      # - name: Run ghp-import
      #   run: |
      #     ghp-import -n -p -f docs/_build/html

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: _build/
      #     force_orphan: true

      - name: deployment
        uses: sphinx-notes/pages@v3